BOOST_INC_DIR = ['/usr/include/boost']
BOOST_LIB_DIR = ['/usr/lib']
BOOST_PYTHON_LIBNAME = ['boost_python-mt']
TAGLIB_INC_DIR = ['/usr/include/taglib']
TAGLIB_LIB_DIR = ['/usr/lib']
TAGLIB_LIBNAME = ['tag']